export const HERO_PORTRAIT_DURATION = 0.85

export const HERO_LABEL_START_DELAY = 0.95
export const HERO_LABEL_STAGGER = 0.12
export const HERO_LABEL_DURATION = 0.45
export const HERO_LABEL_COUNT = 4

export const HERO_STICKER_START_DELAY =
  HERO_LABEL_START_DELAY +
  (HERO_LABEL_COUNT - 1) * HERO_LABEL_STAGGER +
  HERO_LABEL_DURATION +
  0.18
export const HERO_STICKER_STAGGER = 0.14
export const HERO_STICKER_COUNT = 7
export const HERO_STICKER_MOVE_DURATION = 1.15

export const HERO_ARTWORK_START_DELAY =
  HERO_STICKER_START_DELAY +
  (HERO_STICKER_COUNT - 1) * HERO_STICKER_STAGGER +
  HERO_STICKER_MOVE_DURATION +
  0.12
