import cloudinaryImages from "./cloudinary-gallery.json"

export type GalleryImage = {
  id: string
  src: string
  thumbnail: string
  width: number
  height: number
  aspectRatio: number
  blurDataURL?: string
  alt?: string
  variants: { tiny: string; 320: string; 640: string; 960: string }
}

/** Generated by `npm run gallery:upload`; source JPGs remain in public/365. */
export const galleryImages = cloudinaryImages as GalleryImage[]
